### ISSUE TITLE
what about integration with some diff plugins?

### ISSUE THREAD

**Issue by admdh** [morassman/atom-commander#1]
i think one more good feature is integration with some diff plugins, something like dual visual diff))) what do you think? This plugin is really cool by the way! nice job!)))

**Comment by morassman** [comment]
Thanks!

Can you just elaborate a bit on what exactly this will do? There are various kinds of diffs one can do. Does it compare the content of the left and right folders and highlight the differences or is it more something like selecting two files and showing the differences side-by-side in the editor?

**Comment by admdh** [comment]
i think both tools that you described are handy: compare content of the left and right folders, and side-by-side file contents differ with highlighting differences. as for me, i use file contents differ side-by-side more often. for example i have an original file than i have to generate the same file and i need to compare them both side-by-side with highlighting differences so i could be sure they are identical. i was looking for any plugin for atom that will compare side-by-side but didn't find. but there are some plugins for sublime that can compare side-by-side.

**Comment by morassman** [comment]
Sounds good! I will look into it. I see that there are packages that does this kind of comparison.
Thank you for logging your suggestion! I'll add you to my credits list once I've added this.

**Comment by morassman** [comment]
I've spent quite a bit of time on this. I'm able to determine the differences between two files, but the visualisation is starting to take very long. Writing my own panels with line numbers and visual indicators of what's different is too much work. I'm instead making use of Atom's built in text editor. It gives line numbers and markers, but I'm struggling to get the markers to work. I'll try a bit more, but I'll rather integrate with an existing diff plugin. If one ever gets created then let me know about it.

**Comment by morassman** [comment]
I made progress with the editor's markers. Version 0.3.3 now has basic diff functionality. There is still a lot that can be done and I'll continue to improve it, but if a better diff package comes along then I'll rather make use of it. This is the kind of thing that deserves a package of its own:)
