### ISSUE TITLE
Unable to upload file - Atom on Windows

### ISSUE THREAD

**Issue by Evfro** [morassman/atom-commander#10]
I have successfully connected to the server via SFTP and opened remote file for editing. However, when I try to save it and upload back to remote server it gives me an error:
> Reason : Permission denied. The file has been cached and can be uploaded later

Looking in the cache, I can see that file and open its cached version. However, if I hit `Compare` button it gives me
> Error reading remote file. No such file.

This seem to be not a connection problem as I can reopen remote version of the file from the main window once again.

What I noticed is that the filepath for this file in the `Local cache` window is displayed in Windows style  "\home\user\file" instead of Linux style "/home/user/file". Could that be a problem?

**Comment by morassman** [comment]
The file path *may* be the problem. I'll look into it. Please verify the following two things for me. Unfortunately you'll need another FTP client to get this information:

1.) Check to see if you have permission to modify that file. Atom, afaik, doesn't have a "read-only" mode. If it did I'd be able to prevent read-only files from being modified, which would ensure that an upload is never attempted in the first place. If it's a permissions issue then I'll try to find a more elegant way of handling it. I'm planning on adding a "Permissions" column so one can see upfront what it is.

2.) Check to see if the file being accessed is a link to another file.

Knowing these two things will help. Anything else you can think of to reproduce this will be very helpful too.

**Comment by Evfro** [comment]
Thanks!
1) I have tested the upload on ftp://speedtest.tele2.net/upload. It allows upload tests but removes an  uploaded file right after the upload was completed (see http://speedtest.tele2.net). So when I create new file and try to save it there, I get:

>The file /upload/ttt.txt could not be downloaded.
>Reason : Failed to open file

So the reason now is not `permissions denied` which means, I suppose, that file was uploaded but was not found as it was deleted immediately.

Btw, I can create new files and delete them on my original SFTP server without any problems. It's only not possible to modify them.

2) the file is 100% sure not a link to another file as I have created it manually

**Comment by morassman** [comment]
The file path was indeed part of the problem. Well spotted! The fix is part of v0.4.1. Please test with it. Unfortunately I do not have a Windows OS to test with, so fixing such bugs usually takes a bit longer.

**Comment by Evfro** [comment]
Thanks for quick fix!  I confirm, now it doesn't generate the error.

However, even though it states that file upload was successful after saving it, it seems to have no effect on the remote server. The `Upload On Save` feature seems to be broken. Even though I have it enabled, it doesn't actually upload the file, but saves it in the cache. In order to sync changes I have to go to cache and hit `Upload` manually each time the file was edited. It's not a big problem, but would be nice to have it fixed as well, so that files could be uploaded automatically.

**Comment by morassman** [comment]
I found another place where the file path needs to be converted when working on Windows. Hopefully that covers it. I made another small release, v0.4.2. Please try again.
Thanks for the quick testing and feedback!

**Comment by Evfro** [comment]
Perfect! Thanks a lot for the great job! This has fixed the problem and now I can work with remote files seamlessly!

**Comment by morassman** [comment]
I'm glad to hear that:) Thank you for your help with testing. Please log any other issues and feel free to log suggestions for improvements.
