### ISSUE TITLE
Duplicate

### ISSUE THREAD

**Issue by admdh** [morassman/atom-commander#11]
It would be great if there was ability to duplicate files. May be it could be handy to add ability to rename file while duplicating. Or may when you copy one file with F5 add ability to rename files and when coping more than one file just simply copy them without renaming.

**Comment by morassman** [comment]
Specifying the name when copying a single file is something I'm planning on adding. Total Commander and all its other forms do this quite nicely. One of my TODOs is more user interaction when doing file system operations and this will be one of them.

**Comment by morassman** [comment]
Added ability to duplicate files and folders to version 0.6.0. Shift-F5 will duplicate, instead of copy, the highlighted item. This is currently only possible on the local file system.
