### ISSUE TITLE
Extra space

### ISSUE THREAD

**Issue by admdh** [morassman/atom-commander#12]
While atom commander and making it active with F9 or just simply clicking on atom commander to make it active i get extra space under it which is little bit disturbing. I'm using atom on mac os x.
![screen shot 2015-10-20 at 13 03 40](https://cloud.githubusercontent.com/assets/4650029/10605395/4b7667b6-772b-11e5-9a5a-7da6a33200c8.png)

**Comment by morassman** [comment]
I assume "While atom commander" means that it is already visible?

The only time I've seen an issue with spacing was immediately after an update, but after reloading Atom it wouldn't happen again. Even then it wasn't quite what you are seeing.

I tried to reproduce it by pressing F9 while Atom Commander is visible and clicking on it, but wasn't successful. Are you able to reproduce this consistently. If so, please provide more detailed reproduction steps if you can.

**Comment by admdh** [comment]
Yes while atom commander is visible. may be some other plugins can cause this error. Actually it happens randomly but very often. And it seems like everything inside atoms app window jumps to top so i even can't see tabs. But i have reproduced it. So to reproduce it you need to download Color Picker plugin. I have noticed if i turn it off this extra space doesn't appear any more.

**Comment by morassman** [comment]
Thanks. That's very useful to know! I'll look into it.

**Comment by morassman** [comment]
I was able to reproduce it. After debugging a bit I found that the extra space comes from Color Picker. Why it behaves that way in combination with Atom Commander isn't yet clear to me, though. I was able to fix it by editing Color Picker, but I'm going to leave it up to the author to fix it the way he prefers. I'll log a bug for it.

In the mean time you can use the following workaround. When the editor is selected just open the color picker (Cmd-Shift-C). I found that, after opening it at least once, the extra space didn't appear anymore.

**Comment by admdh** [comment]
Thanks!

**Comment by admdh** [comment]
And nice job by the way! Great plugin indeed! It made me switch from sublime text to atom. and it was really hard to switch because sublime is much faster. And thank you for your fast development of new features!!!

**Comment by morassman** [comment]
You're welcome:) It's good to know that it's being used!

**Comment by morassman** [comment]
This was [fixed](https://github.com/thomaslindstrom/color-picker/issues/143) in color-picker v2.1.1. Just update and restart Atom.
