### ISSUE TITLE
Terminal shortcut

### ISSUE THREAD

**Issue by admdh** [morassman/atom-commander#14]
How can i add shortcut for opening terminal?

**Comment by morassman** [comment]
Atom provides the ability to add custom shortcuts to commands in the Command Palette. Atom Commander has a command called "Open Terminal", which means that a shortcut can be added for it. 

Click `Atom` > `Open Your KeyMap` and add something like:
```
'atom-workspace':
  'shift-cmd-t': 'atom-commander:open-terminal'
```
Reload Atom. Pressing Shift-Cmd-T now should open the terminal.

**Comment by admdh** [comment]
Thank you!
