### ISSUE TITLE
Show hidden files and show/follow symlinks

### ISSUE THREAD

**Issue by halloalexkern** [morassman/atom-commander#22]
would be helpful sometimes!

Thanks. Great work, btw.

:-) AK

**Comment by morassman** [comment]
Hi @halloalexkern 

This is suppose to already work when browsing the local file system. When it comes to FTP I'm not sure about hidden files, but symlinks should work.

I develop and test on OSX. Hidden files are shown and symlinks for both files and folders work. I unfortunately don't have a Windows installation, so I'm not sure about the behaviour on it.

Which OS are you using?

**Comment by halloalexkern** [comment]
I'm also on OSX... i'm browsing a SFTP-Server. I can see hidden files, but not my Sym-Soft-Links.
Actually i don't know right now why i wrote something about hidden files :-/

:-) AK

**Comment by morassman** [comment]
Symlinks work with FTP, but there's still a TODO for it in my code when it comes to SFTP. The two libraries unfortunately work differently. I have a vague memory of running into an issue with it, but I can't remember what it was. I'll take a look at it again.

**Comment by morassman** [comment]
It didn't take me long to remember why I left a TODO for it. The way the SFTP library treats symlinks isn't as straight forward as the FTP one. I've added support for it to v0.6.1. I've tested it and both files and folders work. I also tested links to links and they worked as well.
