### ISSUE TITLE
Open in folders project + favorite places bookmarks

### ISSUE THREAD

**Issue by admdh** [morassman/atom-commander#3]
It would be great if there was an option to open in current project's folder. or even may be it would be great if there were favorite places something like bookmarks so anyone could access bookmarks from command plate. this could be handy feature.

**Comment by morassman** [comment]
I agree with the first suggestion and have also considered it. I don't fully understand the the second suggestion though. How do you envision making use of the Command Palette for bookmarks?

**Comment by admdh** [comment]
for example in command palette will be something like "Atom Commander: Bookmarks" or "Atom Commander: Favorite Places" and this will have submenu with list of bookmarks or favorite places. so any one could navigate fast to any favorite folder. something like project manager does with projects - you can toggle projects right from Command Palette.

**Comment by morassman** [comment]
Bookmarks will be added later. Recently another navigation option has been added. From Atom Commander the 'Go' menu has an 'Editor' option. This will navigate to the file that is active in the editor. It is also available from the Command Palette. From the Command Palette choose `Atom Commander: Go Editor` and the same will happen. Just typing `Go Editor` should be sufficient.

**Comment by morassman** [comment]
Support for bookmarks has been added.
