### ISSUE TITLE
A Few Questions about Atom Commander

### ISSUE THREAD

**Issue by toonbon** [morassman/atom-commander#30]
1. I know Ctrl F searches for text in the current buffer.  Is there any way to search for text in a folder?

2. Double-clicking a file opens it in  the editor but you're left in the Atom Commander window and have to select F10 to get to the editor. Is there a way that selecting a file could also switch you to the editor?

3. The compare function shows the differences between files, but is there a way to force a line to be either what's in the left pane or what's in the right pane? 

4. When you open a remote directory, all it shows on top of the pane is the IP.  But I have several folders at the same IP which are distinguished by the login  user name.  Could the user name also be shown for the connection, so I know which connection I'm looking at?   Or if I could just nickname the connections, that would solve he problem also. 

Thanks for your help

**Comment by morassman** [comment]
1. You can search for a file or folder by just starting to type a part of its name, but you can't search for text inside files. This isn't something I'm planning on adding. Or at least, not in the near future.
2. When a file is opened from Atom Commander the editor automatically gains focus. Atom Commander simply remains visible. If the editor is not gaining focus then log a bug. If you would like Atom Commander to hide after opening a file then that would require a change in behaviour. In that case, please log a feature request.
3. This would be possible. The original purpose of this feature was to compare a local file with a remote one just as a check to see if the remote file hasn't been edited by someone else. I don't intend on adding any more functionality such as that provided by diff tools. I'm willing to integrate with an existing package if you know of one that's good though.
4. I suppose a nickname would be nice, but it will require quite a few changes, so I'll rather show the username instead. I've opened a [separate](https://github.com/morassman/atom-commander/issues/31) feature request for this.

**Comment by toonbon** [comment]
Thanks for the response.  I added the request to have Atom Commander hide itself when it opens a file, but didn't see a way to add the "enhancement" label.

**Comment by morassman** [comment]
Thanks. I've added the label. 

PS. You can add labels by clicking the small gear on the right hand side where it says "Labels".
