### ISSUE TITLE
Keep extensions with filename

### ISSUE THREAD

**Issue by toonbon** [morassman/atom-commander#33]
I would much rather have the file extensions appear immediately after the file name - filename.php -  instead of disconnected over on the right in a separate column.  Is there a way to do that?

Thanks

**Comment by morassman** [comment]
I can add a setting that allows one to choose whether the extension should be in its own column or part of the name.

**Comment by toonbon** [comment]
That would be great!

**Comment by morassman** [comment]
I've made it so that you can hide the extension column. In doing so the extension will be shown as part of the filename. The extension column can be hidden from the context menu.

**Comment by toonbon** [comment]
Thanks! That works great.  Now if I have a listing.php file and a listing.js file I don't have to follow them over to the right of the pane to see which one is which.
