### ISSUE TITLE
Atom Commander Panes not behaving sanely

### ISSUE THREAD

**Issue by toonbon** [morassman/atom-commander#34]
First, I have a long line at the bottom of the left pane that has nothing to do with the drives currently loaded into the panes.  Below, for example, there's a line at the bottom of the left pane that is related to an earlier remote directory I had connected to but now there are two local drives in the panes so it shouldn't be there.  Being so long, it covers the text trying to display in the right panel.
![ac1](https://cloud.githubusercontent.com/assets/4875886/17952574/b82b7d72-6a20-11e6-93f8-d02556dc058a.jpg)

Second, I'm not able to predict which pane a GO > Drive will end up in.  Normally the drive is assigned to the pane I right-click to open the context menu.  But I get into modes where no matter which pane I right-click, the drive is always assigned to the left pane, or it is always assigned the right pane.  

Do you know what's going on here?

Thank you for your help.

**Comment by morassman** [comment]
1.) Long line at bottom
AC doesn't produce anything that looks like that. This looks like the status bar at the bottom of Atom's window, which shows the file being edited and has nothing to do with Atom Commander. 

When you open a remote file with AC it downloads it to a local cached directory. As long as the file is open it will remain in the cache even if AC doesn't show the remote folder anymore. It looks like you were editing a file called register_barcode.php?

Can you try and confirm whether this is indeed Atom's status bar?

2.) GO > Drive
I'm aware of this issue. When you use any of the GO commands, the panel that is currently selected will be targeted. When you right click, the context menu simply opens, but it doesn't cause that panel that you clicked on to gain focus. I've tried to fix this, but couldn't intercept the popup to programatically focus the panel that was clicked on.

**Comment by toonbon** [comment]
1.  Yes, I think you're right and that line is from Atom.  If I click it I get a message that looks like it comes from Atom:

![ac5](https://cloud.githubusercontent.com/assets/4875886/17980098/a63771d8-6ab2-11e6-9354-7e287595f536.jpg)

2.  Your answer is enough.  I know now that I just need to click in the panel first before right-clicking and then the drive/connection will go there.

**Comment by morassman** [comment]
Ok cool. I'm gonna close this one then.
