### ISSUE TITLE
Selecting a server connection

### ISSUE THREAD

**Issue by toonbon** [morassman/atom-commander#39]
I have multiple connections I use on the same server, where the only difference is the Username. A few weeks ago this was a problem with Atom Commander because I couldn't tell which connection was open in a panel.  You fixed this  by adding a  Username label at the top right of each panel,:

![ac17](https://cloud.githubusercontent.com/assets/4875886/18618639/b19cf462-7d9f-11e6-9229-edf699ad19d8.jpg)
That was perfect!  But now I'm having the same problem when I try to open a server connection because I don't which connection is which:

![ac16](https://cloud.githubusercontent.com/assets/4875886/18618672/4bf779ec-7da0-11e6-9024-06e505fa75ad.jpg)

Is there a way to show the Username for each connection?

Thanks

**Comment by morassman** [comment]
There isn't currently a way, but I can add it for the next update.

**Comment by toonbon** [comment]
Thank you!

**Comment by morassman** [comment]
Released as part of v0.8.1

**Comment by toonbon** [comment]
I'm running 8.1 but I don't see the usernames in the Servers | Open dialog box:
![ac18](https://cloud.githubusercontent.com/assets/4875886/18810495/d511490a-824c-11e6-8487-55d01b20e3dd.jpg)

**Comment by morassman** [comment]
It works fine on OSX and Windows 10. I've found that the CSS doesn't always refresh properly after an update. Restart Atom and see if it works then.

**Comment by toonbon** [comment]
Ok, I see them now.   But no matter which one I try to open I get the error "Incorrect Credentials" and then  nothing loads.

**Comment by morassman** [comment]
Hmm... I added the ability to use SSH private keys. It might have introduced a bug. I'll look into it.

**Comment by morassman** [comment]
Yeah. A bug did slip in with the new SSH keys feature. I released a patch with the fix, v0.8.2.

I'm not 100% sure, but you _may_ have to recreate your SFTP configs. It's possible for it to have gotten into a broken state due to the bug, but hopefully not. Sorry about that.

**Comment by toonbon** [comment]
Ok.  It looks good.  Thanks.

**Comment by morassman** [comment]
That's great:) Thank you for your feedback!
