### ISSUE TITLE
what about ftp integration?

### ISSUE THREAD

**Issue by admdh** [morassman/atom-commander#4]
what if atom commander was integrated with some ftp plugins?

**Comment by morassman** [comment]
This is something I found very useful in Total Commander and muCommander. It opens up a bit of a can of worms though. I won't be able to use Atom's built in file system API as-is anymore, but will have to add a layer of abstraction to support access to remote sources (and then all the connection handling starts). AFAIK Atom doesn't support editing files over FTP, so special provision will have to be made in that regard as well.

I'm keeping this in the back of my mind, but it is unlikely that it will realise any time soon.

**Comment by morassman** [comment]
Just so you know. I started working on this. The next major update will have FTP and SFTP support. The basics, such as browsing and editing files, will be available, but some of the smaller things like bookmarks might not be supported until the next minor update.

**Comment by morassman** [comment]
v0.4.0 has just been released with FTP and SFTP support. There's bound to be some loose ends, but the basic functionality is there.
