### ISSUE TITLE
New File overwrites with no warning

### ISSUE THREAD

**Issue by toonbon** [morassman/atom-commander#43]
If you create a new file in a pane that already has that file, it overwrites the existing file with a blank file, with no warning. I thought I was creating the file in the other pane, but focus was appaenly in the pane that had the file already, and the file was wiped out. A warning that you're about to overwrite a file would be a help.

**Comment by morassman** [comment]
I'll add a warning to the next version.

**Comment by morassman** [comment]
Added duplicate checking to v0.8.4
