### ISSUE TITLE
Can't create a file under a drive letter

### ISSUE THREAD

**Issue by toonbon** [morassman/atom-commander#44]
I'm not able to create a new file directly under a local drive letter, like C:.  I can, however,  create a new folder under a drive letter and I can create a file in any   folder beneath the drive letter.

**Comment by morassman** [comment]
On Windows you can only create folders in the root, but not files without admin rights. You can see this when using Windows Explorer as well.

I do not have the ability to enable admin rights from Atom Commander. The only thing I can do is to show a message indicating that the operation is not permitted.

**Comment by toonbon** [comment]
Ok.  Thanks.

**Comment by morassman** [comment]
Improved the error handling when creating files in v0.8.4. This will report an error when attempting to create a file in the root on Windows.
