### ISSUE TITLE
Bookmarks in Context menu

### ISSUE THREAD

**Issue by Anders256** [morassman/atom-commander#46]
Hi, 

I wonder if it would be possible to add the bookmarks directly in the Context menu rather then opening a new menu in atom? Not a big issue but is would speed up navigation a bit when jumping between many different bookmarked locations.

Regards,
Anders Bergåker

**Comment by morassman** [comment]
Hey @Anders256 

From Atom's API this seems to possible. I'll look into doing this for the next version.

**Comment by morassman** [comment]
Just released version 0.8.5. The context menu's bookmarks sub-menu will now be populated with the configured bookmarks.

**Comment by Anders256** [comment]
Sorry, forgot to comment. Your solution works fine! Thanks for the update!
