### ISSUE TITLE
Make active with shortcut

### ISSUE THREAD

**Issue by admdh** [morassman/atom-commander#5]
When opening files with atom commander and going back to atom commander (making it active) requires mouse click. it would be great if there was a shortcut to make it active or switch between opened files (tabs) and atom commander.

**Comment by morassman** [comment]
What I have considered doing is to use the same shortcut, F9, to cause Atom Commander to regain focus if it is already open and only when it has focus will F9 actually hide it. Another option is to have an additional shortcut, say F10.

**Comment by morassman** [comment]
Changed F9 to toggle focus between editor and Atom Commander. If the panel is hidden it will be made visible first. Added F10 to toggle visibility. Using F10 to make the panel visible will only show it, but not cause it to gain focus.
