### ISSUE TITLE
Change Color of Vertical Scroll Bar

### ISSUE THREAD

**Issue by toonbon** [morassman/atom-commander#50]
I'd like to change the color of the vertical scroll bar from gray to something bright. By opening Atom n Dev Mode and playing with various styles I've discovered where the color is specified:

![scroll](https://cloud.githubusercontent.com/assets/4875886/20460158/008aaeea-ae90-11e6-9770-29130f6d1d96.jpg)

But I don't now how to put that into styles.less.  I've tried 
![green scrollbar](https://cloud.githubusercontent.com/assets/4875886/20460172/bb62a984-ae90-11e6-8b34-3d141d8bbded.jpg)

but that doesn't work.  

If you happen to know how to do this could maybe nudge me to the answer?

Thanks. 

 (And thanks for the 0.8.4 updates to my previous issues.)

Steve

**Comment by morassman** [comment]
You're welcome :)

There's actually a [post](https://discuss.atom.io/t/change-the-color-and-width-of-editors-sidebar/18545) about this on the forum.

From what is written there I was able to it by adding the following to styles.less:
```
.scrollbars-visible-always .atom-commander {
  /deep/ ::-webkit-scrollbar {
    &-thumb {
      background-color: #15d21c !important;
    }
  }
}
```

**Comment by toonbon** [comment]
Thanks.  Your code worked for Atom Commander and I was able to get what I needed for the Editor from the post.

Steve
