### ISSUE TITLE
Cmder + Atom commander

### ISSUE THREAD

**Issue by IShadowssI** [morassman/atom-commander#51]
Hello, 

i want to know if i can change the cmd.exe ( all the terminal processus thing )  with the beautifull Cmder ^^ 

and if yes, how to do it :) 

Thx you

**Comment by IShadowssI** [comment]
Nevermind, i found the solution myself....  Feel so good <333    ( found it 8 min after my post... My Brain pls, wake up more faster next :p ) 

Thx for the great job and good luck for the future.

/* ####  SOLUTION #### */ 

-> Install Atom commander
-> Go to Packages -> Search "Atom Commander" -> click on him ( yeah, he's a guy, so what  ^^ ) -> View code 

Atom will open a new windows with the full package

-> Right click on Atom commander Folder -> Search 
-> Type cmd.exe and you will see all the files with cmd.exe inside
-> Double click on "wmic.log 33 "  
      -- Replace all the line 33 by your path where is Cmder.exe 
         -- i.e :  line 33 "C:\WINDOWS\system32\cmd.exe"   BY  C:\Users\*******\Desktop\Cmder\Cmder.exe 
-> Do the same thing for line 43 in that same file

 SAVE ! 

-> return to "Project find result"  tab
      -- Select " action.coffee " line 412 
          --  Replace the path by your own path for cmder
                -- ie:   412  command = "start C:\\Windows\\System32\\cmd.exe";   BY 
                           412 C:\\Users\\*******\\Desktop\\Cmder\\Cmder.exe"   DONT FORGET:  " \\ "   not " \ "

Restart Atom and enjoy Cmder in Atom Commander : )

**Comment by morassman** [comment]
:) Awesome! I'm glad you got it working!
