### ISSUE TITLE
Spinner during load and display the name of file being deleted

### ISSUE THREAD

**Issue by toonbon** [morassman/atom-commander#52]
Here are a couple of small things that would make using Atom Commander a more comfortable, for me anyway.

First, whenever I delete a file, say  "load.php" I get the generic prompt "Delete selected files?"  I would much rather see "Delete load.php?"

Second, I have large file I work on that's about 20,000 lines and 830KB.  This file takes about 30 seconds to load into Atom and during that time everything seems frozen.  A spinner or something would be comforting to know that something was happening and the system hasn't actually frozen.

Steve

**Comment by morassman** [comment]
I can do the first one, but not the second. When a file is opened from AC the path of the file is simply given to Atom's API and Atom opens the file. Giving feedback while opening a file is therefore something Atom should be doing.

**Comment by morassman** [comment]
Version 0.8.5 will now show the name of the file or folder in the prompt if only one item is selected.

**Comment by toonbon** [comment]
Excellent!  Thank you.
