### ISSUE TITLE
Kill open finds before going to tree view

### ISSUE THREAD

**Issue by toonbon** [morassman/atom-commander#57]
When going to tree view it would be helpful to first do the ESC operation to kill any open Finds in editor mode. I'm always forgetting to do this manually before going to tree view, and then my double clicks don't work because the screen jumps on the first click.

**Comment by morassman** [comment]
I don't see how this relates to Atom Commander. Neither the tree view nor the find functionality is part of this package. Why are you logging this here?

**Comment by toonbon** [comment]
We've talked about this.  In my case the jump happens when I've gone into tree mode from the editor by hitting F10, after I've used the search function in edit mode.  In that case the search fields are still visible in tree view and cause the jump.  You told me then to hit ESC before leaving edit more, before hitting F10,  and that would close all the Search fields. That works.  I'm just suggesting now that you automatically close the search fields when F10 comes in to go to tree view, since I keep forgetting to do it manually each time.

**Comment by morassman** [comment]
The search view really doesn't have anything to do with Atom Commander. In fact, it's a completely separate package. If you opened the search view manually then you should also close it manually.

I understand that the jumping is a problem, but I have a suspicion that it won't be an issue anymore once you've sorted out the size of the panel as discussed in [this](https://github.com/morassman/atom-commander/issues/56) issue.

Closing the search view to solve the jumping issue is not the way to go.
