### ISSUE TITLE
Expand file name in Diff view

### ISSUE THREAD

**Issue by toonbon** [morassman/atom-commander#58]
It would be helpful if hovering over a file in the Diff tab showed which file it was, the way  hovering over a file in the tree view shows the full file name

![image](https://cloud.githubusercontent.com/assets/4875886/21290070/2f11b280-c462-11e6-8668-7673b97a7006.png)

**Comment by morassman** [comment]
Will add this to the next release. When comparing two local files the full path of each will be shown. When comparing a cached file with its remote counterpart then the path of the remote file will be shown.

**Comment by morassman** [comment]
The changes as described above was released as part of v0.8.6
