### ISSUE TITLE
keyboard navigation

### ISSUE THREAD

**Issue by admdh** [morassman/atom-commander#6]
a - jump to first folder/file which name starts with "a",
b - jump to first folder/file which name starts with "b"
and so on.

**Comment by morassman** [comment]
This is on my TODO list. I'm also considering applying a filter so that only those that match the filter are visible, similar to how the Command Palette works.

**Comment by morassman** [comment]
Added ability to find files and folders by simply starting to type. It works the same way as the Command Palette in that any parts of the name can be entered and the best match will be highlighted.
