### ISSUE TITLE
Column-header

### ISSUE THREAD

**Issue by leomayer** [morassman/atom-commander#66]
After using Atom-commander for a while I find it quite useful but some features are missing:
1) Is it possible to have the header fixed? 
2) Is the idea to sort the columns still intact?
3) Is it possible to enlarge the columns? Sometimes I have had the situation that the Size-column used little bit too much space => enhancing would be great :-)

Features 2) + 3) would require 1)

Which leaves as well the q open, when I save is a tab ==> the sort-order (+column-size) will be memorized?

**Comment by leomayer** [comment]
Or if the issue with the header is next to impossible ==> menu-item with right-click ==> Sort ....

Just as an alternative

**Comment by morassman** [comment]
Hi @leomayer 

1. It is _possible_, but with HTML it's quite a mission. HTML tables do not fix the headers, so one needs to create a custom component or use a third party library. There aren't that many columns, so not being able to see the header all the time shouldn't really cause confusion. This isn't something I plan on doing. I don't feel the effort is worth the gain.
2. Yip. I still would like to add this.
3. The size of the columns are automatically determined based on their content. I'm not sure why the size column would use too much space. It may be a bug. When you see it again, will you please send me a screenshot.

**Comment by leomayer** [comment]
Reg 1) I just made a quick query and found smth on [Stackoverflow](http://stackoverflow.com/questions/4709390/table-header-to-stay-fixed-at-the-top-when-user-scrolls-it-out-of-view-with-jque). But anyway I agree to some extent that usage is limited - especially when currently no additional action is involved (like sorting and changing colum-width)

**Comment by morassman** [comment]
I'll add sorting for the next release, unless there are urgent bugs that needs to be done first, but I'll get to it.

As for the fixed header and column resizing, I'm afraid I'm gonna pass on those. I've been all over stackoverflow myself for help with fixed headers and none of the solutions are pretty.

**Comment by morassman** [comment]
Sorting was added to v0.9.0. You can sort either from the context-menu or by clicking on the header you want to sort by.
