### ISSUE TITLE
Upload file to FTP

### ISSUE THREAD

**Issue by janstieler** [morassman/atom-commander#68]
Hi,
sorry, but how can I upload a file from os window to a ftp window?
Drag N Drop don't work and I don't find a menuitem for it.

Cheers

**Comment by morassman** [comment]
All file system operations need to be done from within atom-commander. There isn't DnD integration with the host OS.

You'll have to navigate to the file you want to upload in one of the panels and then navigate to the FTP folder you want to upload it to in the other panel. You can then copy the local file to the remote folder by selecting it and pressing F5.

**Comment by janstieler** [comment]
Hallo @morassman,
thank you for your quick reply and help!
> All file system operations need to be done from within atom-commander. There isn't DnD integration with the host OS.
I guessed as much.

For the usability it would be good to have also a paste button.
I use the atom on OSX. The copy works only through the button but the paste also with the shortcut cmd+v. A button would make it clear that it should work so.

Cheers
