### ISSUE TITLE
Copy the full name of a file

### ISSUE THREAD

**Issue by leomayer** [morassman/atom-commander#69]
Sometimes I just want to copy'n paste the path of a file. The path itself I can select from the address bar - the name not.
Is there a way to copy (at least) the name to the clipboard - when I press CTRL-C?
Or if the Copy-mechanism might be troublesome - cause one might copy the file itself, the complete path +filename or just the filename - you have an idea how to do it otherwise? (e.g. Context-menu?)
I'm aware that this might cause additional side effects - nevertheless wanna ask...

**Comment by morassman** [comment]
Hi. I'll add this to the next update. I'll make it so that pressing ctrl-p will copy the full path of the selected item.

**Comment by leomayer** [comment]
Just out of curiosity: If I have selected multiple items ==> I get in the clipboard multiple items?

At least this is what I would longing for - but don't know if this is your concept as well ;-)

**Comment by morassman** [comment]
Sure. I'll make it so that the paths of all selected items are copied.

**Comment by morassman** [comment]
Version 0.9.0 was released with this functionality. You can press Ctrl-P to copy the paths of the selected items or just the highlighted item if nothing is selected.

**Comment by morassman** [comment]
Hi @leomayer 

Since you requested this feature I thought I'd let you know. I'm rather going to change the shortcut key from ctrl-p to ctrl-shift-c. This is actually the same shortcut key used by Atom for copying the path of the file open in the focused editor, so it makes sense to use the same shortcut.
