### ISSUE TITLE
Address bar - functionality  

### ISSUE THREAD

**Issue by leomayer** [morassman/atom-commander#70]
Some more ideas reg. the address bar which I personally find quite handy:

1) Is there a chance to have some kind of autocomplete built-in? I'm thinking about something like this [already existing plugin](https://atom.io/packages/autocomplete-paths)

2) I can enter text in the address bar ==> it opens the path  - as long as it is one. But if it is not a path but a valid file ==> Is it possible to 
   - open the file
   - switch the path

3) Is it possible to have some kind of function like history? I'm thinking like in TotalCommander where you have a button - which you click and the history pops up - which you can select and then the path is automatically changed/switched. So, the idea would be to shorten just a tiny little bit the address bar to have a button for the drop-down menu. 
But I'm aware there is the tab functionality already there, so it won't be a big issue if this feature is missing ;-)

**Comment by morassman** [comment]
I'll do nr. 2 for the next release and nr. 3 maybe for the one thereafter. It's unlikely that I'll be doing nr. 1 though.

**Comment by morassman** [comment]
Version 0.9.0 has been released with nr. 2 done.
