### ISSUE TITLE
FTP & Local Folder sync?

### ISSUE THREAD

**Issue by redimongo** [morassman/atom-commander#73]
Just wondering how I can link a project to a certain ftp server, as I don't quite get how I can edit on local files and it syncs to the ftp server.

Currently there is no option to upload a folder or files when I right click.

**Comment by morassman** [comment]
Atom Commander doesn't work with projects in the sense that Atom itself does. It allows you to access files via FTP to edit them directly, but not within the context of a project that is kept in sync with a local one.

I haven't used it myself, but it looks like [remote-ftp](https://atom.io/packages/remote-ftp) is more in line with what you are looking for.
