### ISSUE TITLE
No server list

### ISSUE THREAD

**Issue by antiden** [morassman/atom-commander#76]
After updating, the list of servers is not displayed.

![GitHub Logo](https://antiden.ru/git/atom1.png)
![GitHub Logo](https://antiden.ru/git/atom2.png)

> Atom version 1.17.2 x64

**Comment by antiden** [comment]
This is bag in [Material Theme](https://atom.io/packages/atom-material-ui)

**Comment by morassman** [comment]
I'll check it out a bit, but I'm not sure there's anything I can do about that :(

Strange that a theme would cause this to happen...

**Comment by morassman** [comment]
It doesn't look like there is anything I can do about this on my side :(
