### ISSUE TITLE
Prompts for ssh passphrase when there is none

### ISSUE THREAD

**Issue by joel23888** [morassman/atom-commander#79]
Thanks for a great package. I set up a SFTP server successfully using a private key without passphase but each time I connect or open a file from the remote server I still get asked for a passphrase. I can dismiss this  prompt but would you consider not prompting in the case there is no passphrase?

**Comment by morassman** [comment]
Hi @joel23888. Sorry for taking so long to get back to you.

I think I have found the bug. I'll release a patch shortly.

If this change doesn't fix the problem then there is only one more thing I can think of. When connecting to a server the server may respond with a prompt to request more information. This is typically for a password and/or a passphrase. When that happens I simply respond to it by displaying the prompt that comes from the server and then asks the user to provide whatever it is asking for. I doubt that this would be the problem, but just I thought I'd mention it. Hopefully the change I've made will be the solution.

**Comment by joel23888** [comment]
Thanks for coming back on this. I tested sftp in doing remote-to-local and vice versa from the command line and it works without prompting. I am using the same key on the command line as I do with Atom Commander.

**Comment by morassman** [comment]
Are you still having this problem? I fixed a bug similar to this in v0.10.2, so it might have fixed this issue as well.

**Comment by joel23888** [comment]
Thanks for checking. I am not having the problem anymore.
