### ISSUE TITLE
Don't override command palette hotkey on Mac

### ISSUE THREAD

**Issue by udnaan** [morassman/atom-commander#80]
Copy pathname overrides the command palette hotkey. While the workaround is there to redefine it in user keymaps; it shouldn't be doing it as command palette is one of the most important key for some of us.

**Comment by morassman** [comment]
You're right. I thought about it back when I did it and at least it only overrides within the context of Atom Commander, but in retrospect it wasn't a good idea.

I'll change it to Ctrl-Shift-C for copying file names and Ctrl-Alt-C for copying file paths.

**Comment by udnaan** [comment]
Great!

Great package btw. I can't imagine using atom without it anymore. I hope to see it flourish and become even better over time.

**Comment by morassman** [comment]
Thanks :)

The shortcut keys have been changed in the latest release. It's now:
- Ctrl-Shift-C : Copy file paths
- Ctrl-Alt-C : Copy file names
