### ISSUE TITLE
Edit Bookmarks and Servers not auto completing anymore

### ISSUE THREAD

**Issue by kikoking** [morassman/atom-commander#82]
When selecting the edit or open options you are no longer able to see the associated list, though if I type out the name of a bookmark from memory and click open it will still work.

**Comment by morassman** [comment]
Hello @kikoking 

Sorry. I'm way overdue to replying to you. I've had a similar issue before where the theme that was installed was preventing the popup from showing properly. Can you please tell me what theme you are using?

**Comment by kikoking** [comment]
I think this is the same issue, I had just posted it twice I suppose. I posted the other one as sort of a fix, but I had forgotten that I had posted this as well. So yeah this has already been dealt with.
