### ISSUE TITLE
[feature request] add support for SSH 3 protocol and strong ciphers

### ISSUE THREAD

**Issue by n8v8R** [morassman/atom-commander#92]
Would like utilize this package but the connection fails, which seems due to lack of SSH protocol 3 and/or support for strong ciphers. putty is also not connecting, in case this package is somehow based on it.
```
# Ciphers and keying
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
MACs hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,umac-128-etm@openssh.com
HostKeyAlgorithms ssh-ed25519,ssh-ed25519-cert-v01@openssh.com,ssh-rsa,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com
KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group18-sha512,diffie-hellman-group16-sha512,diffie-hellman-group14-sha256
```

**Comment by morassman** [comment]
Sorry for the long delay in replying. The package doesn't make use of putty. It uses [this](https://www.npmjs.com/package/ssh2) package. There doesn't seem to be an ssh3 version though, so unfortunately I won't be able to support it. At least not yet.
