### ISSUE TITLE
Name Servers

### ISSUE THREAD

**Issue by Dave-Skye** [morassman/atom-commander#94]
Hello

Could you add the option to name servers.

Cheers. - Dave.

**Comment by morassman** [comment]
Sure. I'll try to include it in the next version.

**Comment by SeanAUS120** [comment]
Yes +1 on this idea. 

Especially when connecting by server IP. Hard to keep track of all your servers with just a list of IPs to choose from.

**Comment by morassman** [comment]
Added to v0.12.0
